#ifndef ALCENGINE_MODULE_VULKANHANDLER_PRIVATE_H
#define ALCENGINE_MODULE_VULKANHANDLER_PRIVATE_H

#include <vulkan/vulkan.h>

#include "module/VulkanHandler/VulkanStructBundles.h"

#include <unordered_map>

class VulkanHandlerIMPL {
    public:
        VulkanHandlerIMPL(Registry* registry);
        ~VulkanHandlerIMPL();

        void drawFrame();

    private:
        Registry* registry_ptr = nullptr;

        VkInstance Instance = VK_NULL_HANDLE;
        VkDebugUtilsMessengerEXT DebugMessenger;
        VkSurfaceKHR Surface = VK_NULL_HANDLE;
        VkPhysicalDevice PhysicalDevice = VK_NULL_HANDLE;
        VkDevice Device = VK_NULL_HANDLE;
        struct AlcQueue {
            VkQueue queue;
            uint32_t index;
        };
        AlcQueue GraphicsQueue;
        AlcQueue SurfacePresentQueue;
        VkSwapchainKHR Swapchain = VK_NULL_HANDLE;
            struct windowInfo {
                private:
                    uint32_t Width;
                    uint32_t Height;

                public:
                    const uint32_t& width() const { return Width; }
                    const uint32_t& height() const { return Height; }

                    windowInfo(Registry*& _registry_ptr, VkPhysicalDevice& _PhysicalDevice, VkSurfaceKHR& _Surface);

                    VkExtent2D extent() { return VkExtent2D { .width = width(), .height = height() }; }
            };
            windowInfo* WindowInfo = nullptr; //This represents the swapchain's extent - NOT the actual window size. If actual size changes then this must be regenerated by recreating the swapchain
            std::vector<VkImage> ChainImages;
            std::vector<VkImageView> ChainImageViews;
            VkFormat ChainFormat;
            VkExtent2D ChainExtent;
        VkPipeline Pipeline = VK_NULL_HANDLE;
        VkCommandPool CommandPool = VK_NULL_HANDLE;
            std::vector<VkCommandBuffer> CommandBuffers;
            int max_frames_in_flight = 2;
            int currentFrame = 0;
        std::vector<VkSemaphore> semaphores_presentComplete;
        std::vector<VkSemaphore> semaphores_renderFinished;
        std::vector<VkFence> fences_draw;
        std::vector<VkFence> fences_image;
            
        int Init();

        int CreateVulkanInstance();
            void FetchCreateData(AlcInstanceCreateInfo& ReturnBundle);
            void FetchAppData(AlcApplicationInfo& ReturnBundle);

        int CreateDebugLink();
            void FetchDebugData(AlcDebugUtilsMessengerCreateInfoEXT& ReturnBundle);

            static VKAPI_ATTR VkBool32 VKAPI_CALL VulkanDebugCallback(
                VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity,
                VkDebugUtilsMessageTypeFlagsEXT messageType,
                const VkDebugUtilsMessengerCallbackDataEXT* pCallbackData,
                void* pUserData);

        int CreateSurface();

        int CreateLogicalDevice();
            VkPhysicalDevice SelectPhysicalDevice();
            int ScoreDevice(VkPhysicalDevice _PhysicalDevice);

            void FetchDeviceInfo(AlcDeviceCreateInfo& ReturnBundle);
            void FetchQueueArray(std::vector<AlcDeviceQueueCreateInfo>& ReturnArray);
            void FetchDeviceExtensionArray(std::vector<std::string>& ReturnArray);
            void FetchDeviceFeatures(AlcDeviceFeatures& ReturnBundle);

        int CreateSwapChain();
            int FillSwapchainImages(VkSwapchainCreateInfoKHR& ChainInitInfo);
            void FetchSwapMode(VkPresentModeKHR& ReturnMode);
            void FetchSwapSurfaceFormat(VkFormat& ReturnFormat, VkColorSpaceKHR& ReturnColor);
            int CleanupSwapchain();

        int CreateGraphicsPipeline();
            void FetchShaderStageCreateInfos(std::vector<AlcPipelineShaderStageCreateInfo>& ReturnBundlesArray, VkShaderModule& shaderModule);

        int CreateCommandPool();
            void GetCommandPoolCreateInfo(AlcCommandPoolCreateInfo& ReturnBundle);

        int CreateCommandBuffers();
            void GetCommandBufferCreateInfo(AlcCommandBufferCreateInfo& ReturnBundle);

        int RecordCommandBuffer(VkCommandBuffer& CommandBuffer, int imageIndex);
            struct AlcImageLayoutDetails{
                VkPipelineStageFlags2 stageMask;
                VkAccessFlags2 accessMask;
                VkImageLayout layout;
                uint32_t queueIndex;

                AlcImageLayoutDetails(VkPipelineStageFlags2 _stageMask, VkAccessFlags2 _accessMask, VkImageLayout _layout, uint32_t _queueIndex = VK_QUEUE_FAMILY_IGNORED)
                    :   stageMask(_stageMask),
                        accessMask(_accessMask),
                        layout(_layout),
                        queueIndex(_queueIndex)
                    {}
            };
            
            int TransitionImageLayout(VkCommandBuffer& CommandBuffer, VkImage& _image, AlcImageLayoutDetails& _oldDetails, AlcImageLayoutDetails& _newDetails);

        int AllocateSemaphores(std::vector<VkSemaphore>& semaphores, int count);
        int AllocateFences(std::vector<VkFence>& fences, int count);
};

#endif